version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    container_name: lara_web
    volumes:
      - ./development.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
    ports:
      - "8081:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    container_name: lara_app
    volumes:
      - ./app:/var/www/app
    links:
      - mysql
      - redis
  mysql:
    restart: always
    build:
      context: ./
      dockerfile: mysql.docker
    container_name: lara_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: mysql.env
    ports:
      - "3306:3306"
  redis:
    restart: always
    image: redis:latest
    container_name: lara_redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes